### ISSUE TITLE
It would be helpful if the source provided is the initial version.

### ISSUE THREAD

**Issue by sanket-bhalerao** [mikeckennedy/mongodb-quickstart-course#6]
As i start to go through the tutorial i download the code. and see its the complete code i.e. final snake bnb.
it would be helpful if i can code as the tutorial progress. just having the base structure will be nice on which we can build and complete the code as the session progresses.

**Comment by mikeckennedy** [comment]
Hi @sanket-bhalerao Thanks for the issue. First, heads up that it's been awhile since I went through the videos in sequence, but my recollection is that we start from "file>new project>new python file". That's why we don't have starter code here because that's part of the lessons to build this up as we go from nothing. 

If I'm recalling this wrong, reopen this and I'll update the repo.

**Comment by sanket-bhalerao** [comment]
@mikeckennedy the repository is complete code. in the youtube course, it starts from a halfbaked code, and it starts with completing the code. but when the repo is checked out its complete code.
my be you can do a tag or branch which we can use to follow along with the tutorial
tutorial link: https://www.youtube.com/watch?v=E-1xI85Zog8

**Comment by mikeckennedy** [comment]
Ah, got it. So isn't that the code here:

https://github.com/mikeckennedy/mongodb-quickstart-course/tree/master/src/starter_code_snake_bnb

Best,
Michael
